version: '3'

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"



#chown -R $(whoami):$(whoami) app/
#export UID=${UID} && export GID=${GID}
#docker-compose run app sh -c "django-admin.py startproject app ."